---

name: Devops Project CI pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set short SHA
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t aditya099raj/devops-project:${{ env.SHORT_SHA }} .

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push aditya099raj/devops-project:${{ env.SHORT_SHA }}

      - name: Configure Git Author
        run: |
          git config --global user.name "adidevops"
          git config --global user.email "hello@adidevops.com"
      
      - name: Update Helm chart image tag
        run: |
          sed -i "s/tag: .*/tag: \"${{ env.SHORT_SHA }}\"/" ./devops-project-timer-python-app/values.yaml
          git add ./devops-project-timer-python-app/values.yaml
          git commit -m "Update image tag to ${{ env.SHORT_SHA }}"
          git push
        